use std::{error::Error, fmt, str::FromStr};

use crate::{PtyxisPalette, Rgb, ThemeVariant, Variant};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExportFormat {
    Kitty,
    Ghostty,
    WezTerm,
    Alacritty,
}

impl ExportFormat {
    pub const ALL: [Self; 4] = [Self::Kitty, Self::Ghostty, Self::WezTerm, Self::Alacritty];

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Kitty => "kitty",
            Self::Ghostty => "ghostty",
            Self::WezTerm => "wezterm",
            Self::Alacritty => "alacritty",
        }
    }

    #[must_use]
    pub const fn display_name(self) -> &'static str {
        match self {
            Self::Kitty => "Kitty",
            Self::Ghostty => "Ghostty",
            Self::WezTerm => "WezTerm",
            Self::Alacritty => "Alacritty",
        }
    }

    #[must_use]
    pub const fn extension(self) -> &'static str {
        match self {
            Self::Kitty | Self::Ghostty => "conf",
            Self::WezTerm => "lua",
            Self::Alacritty => "toml",
        }
    }
}

impl fmt::Display for ExportFormat {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl FromStr for ExportFormat {
    type Err = ExportError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.to_ascii_lowercase().as_str() {
            "kitty" => Ok(Self::Kitty),
            "ghostty" => Ok(Self::Ghostty),
            "wezterm" => Ok(Self::WezTerm),
            "alacritty" => Ok(Self::Alacritty),
            _ => Err(ExportError::UnknownFormat(value.to_owned())),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExportedTheme {
    pub format: ExportFormat,
    pub variant: Variant,
    pub suggested_file_name: String,
    pub contents: String,
}

pub fn export_palette(
    palette: &PtyxisPalette,
    variant: Variant,
    format: ExportFormat,
) -> Result<ExportedTheme, ExportError> {
    let colors = palette
        .variant(variant)
        .ok_or(ExportError::MissingVariant(variant))?;
    let foreground = required(colors, "Foreground", variant)?;
    let background = required(colors, "Background", variant)?;
    let cursor = colors.get("Cursor").unwrap_or(foreground);
    let cursor_text = colors.get("CursorForeground").unwrap_or(background);
    let ansi = (0..16)
        .map(|index| required(colors, &format!("Color{index}"), variant))
        .collect::<Result<Vec<_>, _>>()?;
    let ansi: [Rgb; 16] = ansi
        .try_into()
        .expect("the exporter always collects exactly 16 ANSI colors");
    let name = one_line(palette.name());

    let contents = match format {
        ExportFormat::Kitty => kitty(&name, foreground, background, cursor, cursor_text, &ansi),
        ExportFormat::Ghostty => ghostty(&name, foreground, background, cursor, cursor_text, &ansi),
        ExportFormat::WezTerm => wezterm(&name, foreground, background, cursor, cursor_text, &ansi),
        ExportFormat::Alacritty => {
            alacritty(&name, foreground, background, cursor, cursor_text, &ansi)
        }
    };
    let slug = slugify(&name);
    Ok(ExportedTheme {
        format,
        variant,
        suggested_file_name: format!(
            "{slug}-{}-{}.{}",
            variant.as_str(),
            format.as_str(),
            format.extension()
        ),
        contents,
    })
}

fn required(variant: &ThemeVariant, key: &str, kind: Variant) -> Result<Rgb, ExportError> {
    variant.get(key).ok_or_else(|| ExportError::MissingColor {
        variant: kind,
        key: key.to_owned(),
    })
}

fn kitty(
    name: &str,
    foreground: Rgb,
    background: Rgb,
    cursor: Rgb,
    cursor_text: Rgb,
    ansi: &[Rgb; 16],
) -> String {
    let mut output = format!(
        "# {name}\n# Generated by TermiMochi\n\nforeground {foreground}\nbackground {background}\ncursor {cursor}\ncursor_text_color {cursor_text}\n\n"
    );
    for (index, color) in ansi.iter().enumerate() {
        output.push_str(&format!("color{index} {color}\n"));
    }
    output
}

fn ghostty(
    name: &str,
    foreground: Rgb,
    background: Rgb,
    cursor: Rgb,
    cursor_text: Rgb,
    ansi: &[Rgb; 16],
) -> String {
    let mut output = format!(
        "# {name}\n# Generated by TermiMochi\n\nforeground = {foreground}\nbackground = {background}\ncursor-color = {cursor}\ncursor-text = {cursor_text}\n\n"
    );
    for (index, color) in ansi.iter().enumerate() {
        output.push_str(&format!("palette = {index}={color}\n"));
    }
    output
}

fn wezterm(
    name: &str,
    foreground: Rgb,
    background: Rgb,
    cursor: Rgb,
    cursor_text: Rgb,
    ansi: &[Rgb; 16],
) -> String {
    let list = |colors: &[Rgb]| {
        colors
            .iter()
            .map(|color| format!("    '{color}',"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    format!(
        "-- {name}\n-- Generated by TermiMochi\n\nreturn {{\n  foreground = '{foreground}',\n  background = '{background}',\n  cursor_bg = '{cursor}',\n  cursor_fg = '{cursor_text}',\n  cursor_border = '{cursor}',\n  ansi = {{\n{}\n  }},\n  brights = {{\n{}\n  }},\n}}\n",
        list(&ansi[..8]),
        list(&ansi[8..])
    )
}

fn alacritty(
    name: &str,
    foreground: Rgb,
    background: Rgb,
    cursor: Rgb,
    cursor_text: Rgb,
    ansi: &[Rgb; 16],
) -> String {
    const NAMES: [&str; 8] = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
    ];
    let color_table = |colors: &[Rgb]| {
        NAMES
            .iter()
            .zip(colors)
            .map(|(name, color)| format!("{name} = \"{color}\""))
            .collect::<Vec<_>>()
            .join("\n")
    };
    format!(
        "# {name}\n# Generated by TermiMochi\n\n[colors.primary]\nforeground = \"{foreground}\"\nbackground = \"{background}\"\n\n[colors.cursor]\ntext = \"{cursor_text}\"\ncursor = \"{cursor}\"\n\n[colors.normal]\n{}\n\n[colors.bright]\n{}\n",
        color_table(&ansi[..8]),
        color_table(&ansi[8..])
    )
}

fn one_line(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn slugify(value: &str) -> String {
    let mut output = String::new();
    let mut separator_pending = false;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if separator_pending && !output.is_empty() {
                output.push('-');
            }
            output.push(character.to_ascii_lowercase());
            separator_pending = false;
        } else if !output.is_empty() {
            separator_pending = true;
        }
    }
    if output.is_empty() {
        output.push_str("termimochi");
    }
    output
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ExportError {
    UnknownFormat(String),
    MissingVariant(Variant),
    MissingColor { variant: Variant, key: String },
}

impl fmt::Display for ExportError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownFormat(format) => write!(formatter, "unknown export format {format:?}"),
            Self::MissingVariant(variant) => write!(formatter, "palette has no {variant} variant"),
            Self::MissingColor { variant, key } => {
                write!(formatter, "{variant} variant is missing {key}")
            }
        }
    }
}

impl Error for ExportError {}

#[cfg(test)]
mod tests {
    use super::*;

    const PALETTE: &str = include_str!("../fixtures/fog-paper-codex.palette");

    fn sentinel_palette() -> (PtyxisPalette, Vec<Rgb>) {
        let mut input = String::from(
            "[Palette]\nName=Sentinel\n[Light]\nForeground=#010203\nBackground=#040506\n\
             Cursor=#070809\nCursorForeground=#0A0B0C\n",
        );
        let ansi = (0_u8..16)
            .map(|index| Rgb::new(0x20 + index, 0x40 + index, 0x60 + index))
            .collect::<Vec<_>>();
        for (index, color) in ansi.iter().enumerate() {
            input.push_str(&format!("Color{index}={color}\n"));
        }
        (PtyxisPalette::from_text(&input).unwrap(), ansi)
    }

    fn assert_exact_line(contents: &str, expected: &str) {
        assert!(
            contents.lines().any(|line| line == expected),
            "missing exact line {expected:?} in:\n{contents}"
        );
    }

    fn lua_color_array<'a>(contents: &'a str, key: &str) -> Vec<&'a str> {
        let marker = format!("  {key} = {{\n");
        let (_, tail) = contents
            .split_once(&marker)
            .unwrap_or_else(|| panic!("missing Lua array {key:?}"));
        let (body, _) = tail
            .split_once("\n  },")
            .unwrap_or_else(|| panic!("unterminated Lua array {key:?}"));
        body.lines()
            .map(|line| line.trim().trim_end_matches(',').trim_matches('\''))
            .collect()
    }

    fn toml_section<'a>(contents: &'a str, name: &str) -> &'a str {
        let marker = format!("[{name}]\n");
        let (_, tail) = contents
            .split_once(&marker)
            .unwrap_or_else(|| panic!("missing TOML section {name:?}"));
        tail.split("\n[").next().unwrap()
    }

    #[test]
    fn every_export_contains_all_semantic_colors() {
        let palette = PtyxisPalette::from_text(PALETTE).unwrap();
        for format in ExportFormat::ALL {
            let exported = export_palette(&palette, Variant::Light, format).unwrap();
            assert!(exported.contents.contains("#252B33"), "{format}");
            assert!(exported.contents.contains("#E7E8E5"), "{format}");
            for index in 0..16 {
                let color = palette
                    .variant(Variant::Light)
                    .unwrap()
                    .get(&format!("Color{index}"))
                    .unwrap();
                assert!(
                    exported.contents.contains(&color.to_hex()),
                    "{format} Color{index}"
                );
            }
            assert!(exported.suggested_file_name.contains("light"));
        }
    }

    #[test]
    fn format_specific_contracts_are_emitted() {
        let palette = PtyxisPalette::from_text(PALETTE).unwrap();
        let kitty = export_palette(&palette, Variant::Dark, ExportFormat::Kitty).unwrap();
        assert!(kitty.contents.contains("cursor_text_color #171C24"));
        assert!(kitty.contents.contains("color15 #F7F9FB"));

        let ghostty = export_palette(&palette, Variant::Dark, ExportFormat::Ghostty).unwrap();
        assert!(ghostty.contents.contains("palette = 15=#F7F9FB"));

        let wezterm = export_palette(&palette, Variant::Dark, ExportFormat::WezTerm).unwrap();
        assert!(wezterm.contents.contains("cursor_border = '#79BFE8'"));
        assert_eq!(wezterm.contents.matches("    '#").count(), 16);

        let alacritty = export_palette(&palette, Variant::Dark, ExportFormat::Alacritty).unwrap();
        assert!(alacritty.contents.contains("[colors.normal]"));
        assert!(alacritty.contents.contains("[colors.bright]"));
    }

    #[test]
    fn every_export_maps_each_sentinel_to_its_target_key() {
        const NAMES: [&str; 8] = [
            "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        ];
        let (palette, ansi) = sentinel_palette();

        let kitty = export_palette(&palette, Variant::Light, ExportFormat::Kitty).unwrap();
        for expected in [
            "foreground #010203",
            "background #040506",
            "cursor #070809",
            "cursor_text_color #0A0B0C",
        ] {
            assert_exact_line(&kitty.contents, expected);
        }
        for (index, color) in ansi.iter().enumerate() {
            assert_exact_line(&kitty.contents, &format!("color{index} {color}"));
        }

        let ghostty = export_palette(&palette, Variant::Light, ExportFormat::Ghostty).unwrap();
        for expected in [
            "foreground = #010203",
            "background = #040506",
            "cursor-color = #070809",
            "cursor-text = #0A0B0C",
        ] {
            assert_exact_line(&ghostty.contents, expected);
        }
        for (index, color) in ansi.iter().enumerate() {
            assert_exact_line(&ghostty.contents, &format!("palette = {index}={color}"));
        }

        let wezterm = export_palette(&palette, Variant::Light, ExportFormat::WezTerm).unwrap();
        for expected in [
            "  foreground = '#010203',",
            "  background = '#040506',",
            "  cursor_bg = '#070809',",
            "  cursor_fg = '#0A0B0C',",
            "  cursor_border = '#070809',",
        ] {
            assert_exact_line(&wezterm.contents, expected);
        }
        let expected_ansi = ansi.iter().map(|color| color.to_hex()).collect::<Vec<_>>();
        assert_eq!(
            lua_color_array(&wezterm.contents, "ansi"),
            expected_ansi[..8]
        );
        assert_eq!(
            lua_color_array(&wezterm.contents, "brights"),
            expected_ansi[8..]
        );

        let alacritty = export_palette(&palette, Variant::Light, ExportFormat::Alacritty).unwrap();
        let primary = toml_section(&alacritty.contents, "colors.primary");
        assert_exact_line(primary, "foreground = \"#010203\"");
        assert_exact_line(primary, "background = \"#040506\"");
        let cursor = toml_section(&alacritty.contents, "colors.cursor");
        assert_exact_line(cursor, "text = \"#0A0B0C\"");
        assert_exact_line(cursor, "cursor = \"#070809\"");
        let normal = toml_section(&alacritty.contents, "colors.normal");
        let bright = toml_section(&alacritty.contents, "colors.bright");
        for (index, name) in NAMES.iter().enumerate() {
            assert_exact_line(normal, &format!("{name} = \"{}\"", ansi[index]));
            assert_exact_line(bright, &format!("{name} = \"{}\"", ansi[index + 8]));
        }
    }

    #[test]
    fn incomplete_palette_cannot_be_exported() {
        let palette = PtyxisPalette::from_text(
            "[Palette]\nName=Tiny\n[Light]\nForeground=#000000\nBackground=#ffffff\n",
        )
        .unwrap();
        assert!(matches!(
            export_palette(&palette, Variant::Light, ExportFormat::Kitty),
            Err(ExportError::MissingColor { .. })
        ));
    }
}
